apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-cluster1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: blog
  source:
    repoURL: git@192.168.31.50:gaamingzhang/gaamingblogkubernetesargocd.git
    targetRevision: HEAD
    path: apps/blog/cluster1
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
