apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog
  namespace: argocd
spec:
  description: Blog application project
  sourceRepos:
  - '*'
  destinations:
  - namespace: blog
    server: https://kubernetes.default.svc
  - namespace: blog
    name: cluster2
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: networking.k8s.io
    kind: '*'
