apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
- ../../base
- ingress-prod.yaml
- ingress-canary.yaml

images:
- name: gaaming/blog
  newName: 192.168.31.30:30002/gaaming/blog

commonLabels:
  cluster: cluster1
